### ISSUE TITLE
The slug for each video should actually represent the title of the video

### ISSUE THREAD

**Issue by unicodeveloper** [andela-oisola/techlms#3]
For instance, for `Learn C` video, the slug should be something like `learn-c`, for the wordpress tutorial video, the slug should be something like `wordpress-tutorial`. When I access the video, the url should be something like `http://tech-lms.herokuapp.com/videos/wordpress-tutorial ` 

<img width="1118" alt="screen shot 2015-12-01 at 10 39 45 am" src="https://cloud.githubusercontent.com/assets/2946769/11494923/f0acb3a4-9817-11e5-9519-302e0189e486.png">

Same goes for the category too.

<img width="1119" alt="screen shot 2015-12-01 at 11 03 26 am" src="https://cloud.githubusercontent.com/assets/2946769/11495317/379cca76-981b-11e5-9205-f530747782ac.png">

**Comment by andela-oisola** [comment]
This was like this during my defence and you didn't point to it. I think
all corrections you are meant to point to now are the ones you said I
should effect during defence.

*Oladipupo Isola | Software Developer, Andela*
*See what TechCrunch
<http://techcrunch.com/2015/06/25/backed-by-spark-capital-andela-will-develop-a-continent-of-tech-talent/>
and StackOverflow
<http://blog.stackoverflow.com/2015/05/stack-overflow-and-andela-partner-to-provide-education-beyond-borders/>
say
about us!*
(c) +234-703-302-0216 | Andela.com <http://andela.com/>

**Comment by unicodeveloper** [comment]
Yeah, I bet that was an oversight on my part. I already concluded that you wouldn't have your urls that way but unfortunately I was wrong!

**Comment by andela-oisola** [comment]
Okay. Since I am aware of what was done by those before me, I think this
new standard should effected for those after to avoid any form of
unfairness because as it stands things are not fair here.

*Oladipupo Isola | Software Developer, Andela*
*See what TechCrunch
<http://techcrunch.com/2015/06/25/backed-by-spark-capital-andela-will-develop-a-continent-of-tech-talent/>
and StackOverflow
<http://blog.stackoverflow.com/2015/05/stack-overflow-and-andela-partner-to-provide-education-beyond-borders/>
say
about us!*
(c) +234-703-302-0216 | Andela.com <http://andela.com/>

**Comment by unicodeveloper** [comment]
What makes us #TIA is the ability to get better at what we do. Those guys might have scaled through but i have learned lessons from what they did and also great feedback.

Actually, this is really the first opportunity for you to show your UI/UX skills and it's obvious you have a lot to improve on.

It might not be convenient for you and I totally understand that but continous learning is what makes us better persons.

**Comment by andela-oisola** [comment]
Really, it is not convenient for me. But one of my basic questions now is
why you chose not to tell these on Friday or yesterday. Why you chose 1st
of December to give me a reply. I could have taken my time to complete it
instead of aiming to deliver it by the end of November.

Nonetheless, I am always open to getting better as you stated there.

*Oladipupo Isola | Software Developer, Andela*
*See what TechCrunch
<http://techcrunch.com/2015/06/25/backed-by-spark-capital-andela-will-develop-a-continent-of-tech-talent/>
and StackOverflow
<http://blog.stackoverflow.com/2015/05/stack-overflow-and-andela-partner-to-provide-education-beyond-borders/>
say
about us!*
(c) +234-703-302-0216 | Andela.com <http://andela.com/>

**Comment by unicodeveloper** [comment]
I was busy with several other things on Friday and on Monday.

**Comment by andela-oisola** [comment]
There I was reminding you occasionally about it on Slack and you chose not
to give me this reason or any other form of reply on Slack. It is well.
Have a great day!

*Oladipupo Isola | Software Developer, Andela*
*See what TechCrunch
<http://techcrunch.com/2015/06/25/backed-by-spark-capital-andela-will-develop-a-continent-of-tech-talent/>
and StackOverflow
<http://blog.stackoverflow.com/2015/05/stack-overflow-and-andela-partner-to-provide-education-beyond-borders/>
say
about us!*
(c) +234-703-302-0216 | Andela.com <http://andela.com/>
