### ISSUE TITLE
There's too much white space around

### ISSUE THREAD

**Issue by unicodeveloper** [andela-oisola/techlms#4]
Also, I think the video should be centered, take a look at egghead.io
<img width="1116" alt="screen shot 2015-12-01 at 10 53 32 am" src="https://cloud.githubusercontent.com/assets/2946769/11495140/cd02016e-9819-11e5-91fe-301b571ceb0e.png">

<img width="1120" alt="screen shot 2015-12-01 at 10 52 50 am" src="https://cloud.githubusercontent.com/assets/2946769/11495189/33bf744a-981a-11e5-9059-e739fdcfecda.png">

**Comment by andela-oisola** [comment]
I have been seeking feedback since Friday. And also, all these were not
said or stated in Checkpoint requirement document. I think you should allow
state that this is not fair.

*Oladipupo Isola | Software Developer, Andela*
*See what TechCrunch
<http://techcrunch.com/2015/06/25/backed-by-spark-capital-andela-will-develop-a-continent-of-tech-talent/>
and StackOverflow
<http://blog.stackoverflow.com/2015/05/stack-overflow-and-andela-partner-to-provide-education-beyond-borders/>
say
about us!*
(c) +234-703-302-0216 | Andela.com <http://andela.com/>

**Comment by unicodeveloper** [comment]
You mean, the checkpoint requirement document should tell you specifically how various parts of your UI should look like?

**Comment by andela-oisola** [comment]
Well, I have others I reference to. Since there's nowhere it is stated how
it should look like, it means discretion is allowed on my part. And it
should not be what will hinder me.

*Oladipupo Isola | Software Developer, Andela*
*See what TechCrunch
<http://techcrunch.com/2015/06/25/backed-by-spark-capital-andela-will-develop-a-continent-of-tech-talent/>
and StackOverflow
<http://blog.stackoverflow.com/2015/05/stack-overflow-and-andela-partner-to-provide-education-beyond-borders/>
say
about us!*
(c) +234-703-302-0216 | Andela.com <http://andela.com/>

**Comment by unicodeveloper** [comment]
Discretion is very much allowed, it allows for creativity. Now, feedback for that discretion is also allowed and that's exactly what I am dishing out to you. 

I hope i'm not getting the vibe that you just want to finish the checkpoint and jump into D1 by all means. If you are not willing to be receptive to feedback, then I'm sorry to clearly state that you aren't going nowhere until your UI/UX skills is of acceptable standard.

**Comment by andela-oisola** [comment]
I agree with that. There is nothing wrong at all with giving and accepting
feedback. But we both know I could have been given since Friday. That's my
sole concern. If it's one month it takes to prove my skills or even two, I
am well open to that.

*Oladipupo Isola | Software Developer, Andela*
*See what TechCrunch
<http://techcrunch.com/2015/06/25/backed-by-spark-capital-andela-will-develop-a-continent-of-tech-talent/>
and StackOverflow
<http://blog.stackoverflow.com/2015/05/stack-overflow-and-andela-partner-to-provide-education-beyond-borders/>
say
about us!*
(c) +234-703-302-0216 | Andela.com <http://andela.com/>

**Comment by unicodeveloper** [comment]
You still didnt fix this. You can center the video, let the title of the video be on top and the decription could be below

**Comment by unicodeveloper** [comment]
This is another good example in how it can be positioned in a way that evenly maximizes the space
<img width="1017" alt="screen shot 2015-12-08 at 8 48 50 am" src="https://cloud.githubusercontent.com/assets/2946769/11648750/8c915890-9d88-11e5-938d-6095a91ddcc1.png">
